name: Update gist with WakaTime stats

on:
  push:
    branches:
      - main
  watch:
    types:
      - started
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 05dd65c8a861774a0120d13e34c0ac3a
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
